PORT_A   EQU 2A0H
PORT_C   EQU 2A2H
PORT_CTL EQU 2A3H
;0809端口地址
PORT_IN4 EQU 284H
;0832端口地址
PORT_DA  EQU 288H

CODE SEGMENT
    ASSUME CS:CODE
START:
    MOV AL, 00H
    MOV DX, PORT_DA
UP:
    OUT DX, AL
    INC AL
    TEST AL, 0FFH
    JZ UP
    MOV BX, 2000H
    DELAY1:
        MOV CX, 200H
        DELAY11: LOOP DELAY11
        DEC BX
        JNZ DELAY1 
    DEC AL
DOWN:
    OUT DX, AL
    DEC AL
    CMP AL, 00H
    JNZ DOWN
    MOV BX, 2000H
    DELAY2:
        MOV CX, 200H
        DELAY22: LOOP DELAY22
        DEC BX
        JNZ DELAY2 
    JZ UP
CODE ENDS
    END 